--
-- PostgreSQL database dump
--

\restrict 4ZjmO28PekqzwUM1ysxmDPuO245VRlTePTCZENo97d4uCaGAeS1EcTxIzcopAOG

-- Dumped from database version 18.6 (Ubuntu 18.6-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-1.pgdg24.04+2)

-- Started on 2026-08-17 22:28:02 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 22424)
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    customer_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    password character varying(60) NOT NULL,
    username character varying(20) NOT NULL,
    person_id bigint NOT NULL
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 22423)
-- Name: customers_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 22438)
-- Name: persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persons (
    person_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    address character varying(255),
    age integer,
    gender character(1),
    identification character varying(10) NOT NULL,
    lastname character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    telephone character varying(10)
);


ALTER TABLE public.persons OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 22437)
-- Name: persons_person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persons ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 22454)
-- Name: registros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registros (
    registro_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    fecha timestamp without time zone NOT NULL,
    ignicion boolean,
    latitud numeric(10,8),
    longitud numeric(11,8),
    odometro numeric(12,2),
    velocidad numeric(6,2),
    imei character varying(20) NOT NULL
);


ALTER TABLE public.registros OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 22453)
-- Name: registros_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registros ALTER COLUMN registro_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registros_registro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 22467)
-- Name: role_customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_customers (
    role_customer_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    customer_id bigint NOT NULL,
    rol_id bigint NOT NULL
);


ALTER TABLE public.role_customers OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 22466)
-- Name: role_customers_role_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_customers ALTER COLUMN role_customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_customers_role_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 22480)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 22479)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 22491)
-- Name: vehiculos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehiculos (
    imei character varying(20) NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    creation_host character varying(50) NOT NULL,
    creation_user character varying(50) NOT NULL,
    modification_date timestamp without time zone,
    modification_host character varying(50),
    modification_user character varying(50),
    status boolean NOT NULL,
    agencia character varying(100),
    chasis character varying(50),
    dealer character varying(100),
    marca character varying(50),
    modelo character varying(50),
    placa character varying(20) NOT NULL,
    plataforma character varying(50),
    customer_id bigint
);


ALTER TABLE public.vehiculos OWNER TO postgres;

--
-- TOC entry 3498 (class 0 OID 22424)
-- Dependencies: 220
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.customers VALUES (1, '2026-08-17 22:19:34.254306', '127.0.0.1', 'admin', NULL, NULL, NULL, true, '$2a$10$itMT/hPoLNo/FqNuzh69LeNMMUsca/j2WIdOn7P0ZYhjs6rKK/way', 'admin', 1);


--
-- TOC entry 3500 (class 0 OID 22438)
-- Dependencies: 222
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.persons VALUES (1, '2026-08-17 22:19:34.246311', '127.0.0.1', 'admin', NULL, NULL, NULL, true, 'La Concepción', 36, 'M', '1717172631', 'Administrador', 'Administrador', '0987350473');


--
-- TOC entry 3502 (class 0 OID 22454)
-- Dependencies: 224
-- Data for Name: registros; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.registros VALUES (1, '2026-08-17 22:19:34.285352', '127.0.0.1', 'admin', NULL, NULL, NULL, true, '2026-08-17 22:19:34.285352', true, -0.18065300, -78.46783800, 12500.75, 45.50, '864209041234567');
INSERT INTO public.registros VALUES (2, '2026-08-17 22:19:34.293588', '127.0.0.1', 'admin', NULL, NULL, NULL, true, '2026-08-17 22:19:34.293588', true, -2.17099800, -79.92235900, 34200.50, 60.00, '864209047654321');


--
-- TOC entry 3504 (class 0 OID 22467)
-- Dependencies: 226
-- Data for Name: role_customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role_customers VALUES (1, '2026-08-17 22:19:34.265617', '127.0.0.1', 'admin', NULL, NULL, NULL, true, 1, 1);


--
-- TOC entry 3506 (class 0 OID 22480)
-- Dependencies: 228
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles VALUES (1, '2026-08-17 22:19:34.260002', '127.0.0.1', 'admin', NULL, NULL, NULL, true, 'ROLE_ADMIN');


--
-- TOC entry 3507 (class 0 OID 22491)
-- Dependencies: 229
-- Data for Name: vehiculos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.vehiculos VALUES ('864209041234567', '2026-08-17 22:19:34.272076', '127.0.0.1', 'admin', NULL, NULL, NULL, true, 'Agencia Cumbayá', 'CHS98765432101', 'Dealer Quito', 'Chevrolet', 'Grand Vitara', 'PBA-1234', 'TrackGps', 1);
INSERT INTO public.vehiculos VALUES ('864209047654321', '2026-08-17 22:19:34.278425', '127.0.0.1', 'admin', NULL, NULL, NULL, true, 'Agencia Samborondón', 'CHS98765432102', 'Dealer Guayaquil', 'Toyota', 'Hilux', 'PBB-5678', 'FleetNav', 1);


--
-- TOC entry 3513 (class 0 OID 0)
-- Dependencies: 219
-- Name: customers_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_customer_id_seq', 1, true);


--
-- TOC entry 3514 (class 0 OID 0)
-- Dependencies: 221
-- Name: persons_person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persons_person_id_seq', 1, true);


--
-- TOC entry 3515 (class 0 OID 0)
-- Dependencies: 223
-- Name: registros_registro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registros_registro_id_seq', 2, true);


--
-- TOC entry 3516 (class 0 OID 0)
-- Dependencies: 225
-- Name: role_customers_role_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_customers_role_customer_id_seq', 1, true);


--
-- TOC entry 3517 (class 0 OID 0)
-- Dependencies: 227
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, true);


--
-- TOC entry 3332 (class 2606 OID 22436)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (customer_id);


--
-- TOC entry 3334 (class 2606 OID 22452)
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (person_id);


--
-- TOC entry 3338 (class 2606 OID 22465)
-- Name: registros registros_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registros
    ADD CONSTRAINT registros_pkey PRIMARY KEY (registro_id);


--
-- TOC entry 3340 (class 2606 OID 22478)
-- Name: role_customers role_customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_customers
    ADD CONSTRAINT role_customers_pkey PRIMARY KEY (role_customer_id);


--
-- TOC entry 3342 (class 2606 OID 22490)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 3336 (class 2606 OID 22505)
-- Name: persons uk_q9hehhi7b6xsv7sp8cpb4mo21; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT uk_q9hehhi7b6xsv7sp8cpb4mo21 UNIQUE (identification);


--
-- TOC entry 3344 (class 2606 OID 22503)
-- Name: vehiculos vehiculos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT vehiculos_pkey PRIMARY KEY (imei);


--
-- TOC entry 3347 (class 2606 OID 22516)
-- Name: role_customers fk2e6sti0ghk63ki33k5uonbtu8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_customers
    ADD CONSTRAINT fk2e6sti0ghk63ki33k5uonbtu8 FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id);


--
-- TOC entry 3345 (class 2606 OID 22506)
-- Name: customers fk2wkt5i862ljgauvs6mtjh8d8v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fk2wkt5i862ljgauvs6mtjh8d8v FOREIGN KEY (person_id) REFERENCES public.persons(person_id);


--
-- TOC entry 3348 (class 2606 OID 22521)
-- Name: role_customers fk3orxa5tagh4lgiw4vx7s911q3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_customers
    ADD CONSTRAINT fk3orxa5tagh4lgiw4vx7s911q3 FOREIGN KEY (rol_id) REFERENCES public.roles(role_id);


--
-- TOC entry 3346 (class 2606 OID 22511)
-- Name: registros fk6p7y79hv53487kg7qfwcdnqhr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registros
    ADD CONSTRAINT fk6p7y79hv53487kg7qfwcdnqhr FOREIGN KEY (imei) REFERENCES public.vehiculos(imei);


--
-- TOC entry 3349 (class 2606 OID 22526)
-- Name: vehiculos fkona2h2ydx0r01d6xnnov5bmiu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT fkona2h2ydx0r01d6xnnov5bmiu FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id);


-- Completed on 2026-08-17 22:28:02 -05

--
-- PostgreSQL database dump complete
--

\unrestrict 4ZjmO28PekqzwUM1ysxmDPuO245VRlTePTCZENo97d4uCaGAeS1EcTxIzcopAOG

